

const USER_LOGIN_REQUESTS = 'USER_LOGIN_REQUESTS'
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'



const USER_REGISTER_REQUESTS = 'USER_REGISTER_REQUESTS'
const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'


const USER_UPDATE_REQUESTS = 'USER_UPDATE_REQUESTS'
const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED'


const USER_LOGOUT = 'USER_LOGOUT'


export {
    USER_LOGIN_REQUESTS,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,
    USER_LOGOUT,
    USER_REGISTER_REQUESTS,
    USER_REGISTER_SUCCESS,
    USER_REGISTER_FAILED,
    USER_UPDATE_REQUESTS,
    USER_UPDATE_SUCCESS,
    USER_UPDATE_FAILED,

}