const USER_LOGIN_REQUESTS = 'USER_LOGIN_REQUESTS'
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'


const USER_REGISTER_REQUESTS = 'USER_REGISTER_REQUESTS'
const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'


const USER_UPDATE_REQUESTS = 'USER_UPDATE_REQUESTS'
const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED'

const USER_REFRESH = 'USER_REFRESH'


const USER_TOKEN_REQUESTS = 'USER_TOKEN_REQUESTS'
const USER_TOKEN_SUCCESS = 'USER_TOKEN_SUCCESS'
const USER_TOKEN_FAILED = 'USER_TOKEN_FAILED'

const USER_GOOGLE_REQUESTS = 'USER_GOOGLE_REQUESTS'
const USER_GOOGLE_FAILED = 'USER_GOOGLE_FAILED'

const USER_LOGOUT_REQUESTS = 'USER_LOGOUT_REQUESTS'
const USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED'
const USER_LOGOUT = 'USER_LOGOUT'


export {
    USER_LOGIN_REQUESTS,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,
    USER_LOGOUT,
    USER_REGISTER_REQUESTS,
    USER_REGISTER_SUCCESS,
    USER_REGISTER_FAILED,
    USER_UPDATE_REQUESTS,
    USER_UPDATE_SUCCESS,
    USER_UPDATE_FAILED,
    USER_REFRESH,
    USER_TOKEN_REQUESTS,
    USER_TOKEN_SUCCESS,
    USER_TOKEN_FAILED,
    USER_GOOGLE_REQUESTS,
    USER_GOOGLE_FAILED,
    USER_LOGOUT_REQUESTS,
    USER_LOGOUT_FAILED

}